api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

app_name = "api"

urlpatterns = [
    # TOKEN
    path('auth/', obtain_auth_token),
    path('token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name = 'token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name = 'token_verify'),
    # END TOKEN

    path('search/', views.search_list_api_view, name = 'search'),
    # _________ INVENTORY APP URLS _____________
    path('category/', views.categories_api_view, name = "category-list"),
    path('products_by_category/<slug:slug>/', views.products_api_view_by_category, name = 'products-by-category'),
    path('products_category_child/<slug:slug>/', views.products_api_view_by_category_child, name = "product-detail-by-categorychild"),
    path('product_detail/<slug:slug>/', views.product_detail_api_view, name = 'product-detail'),
    path('images/<int:id>/', views.media_images_api_view, name = 'media-images'),
    # _________ END INVENTORY APP URLS _____________

    # _________ ACCOUNT APP URLS _____________
    path('customers/', views.customers_api__get_view, name = 'customers'),
    path('customer/addresses/<int:id>/', views.addresses_api_get_view, name = 'customer-addresses'),
    path('customer/address_detail/<slug:id>/', views.address_api_get_view, name = 'address-detail'),
    # _________ END ACCOUNT APP URLS _____________

    # _________ CHECKOUT APP URLS _____________
    path('deliveries/', views.deliveries_api_view_get, name = 'delivery-list'),
    path('delivery_detail/<int:id>/', views.DeliveryRetrieveApiView.as_view(), name = 'delivery-detail'),
    # _________ END CHECKOUT APP URLS _____________
    
    # _________ ORDERS APP URLS _____________
    path('orders/<int:id>/', views.orders_api_view_get, name = 'orders'),
    path('order/<int:id>/', views.order_api_view_get, name = 'order-detail'),
    path('items/<int:id>/', views.orderitems_api_view_get, name = 'order-items'),
    path("item/<int:id>/", views.orderitem_api_view_get, name = 'item-detail'),

    # _________ END ORDERS APP URLS _____________
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_list, name = 'list'),
    path('add/', views.add_basket, name = 'add_to_basket'),
    path('update/', views.update_basket, name = 'update_basket'),
    path('remove/', views.delete_basket, name = 'delete_basket'),
    #DELIVERY OPTIONS
    path('udpate_delivery/', views.basket_update_delivery, name = "basket-update-delivery"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include('inventory.urls', namespace='inventory')),
    path('basket/', include('basket.urls', namespace="basket")),
    path('account/', include('account.urls', namespace="account")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlist")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    
    # API
    path("api/", include("api.urls", namespace="api")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

inventory/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500
from . import views

app_name = 'inventory'



urlpatterns = [
    path('', views.products, name = 'list-products'),
    path('best_selling/', views.get_best_selling_products, name = 'best-products'),
    path('list/', views.get_fake),
    path('products/<slug:slug>/', views.products_by_category, name = 'products-by-category'),
    path('product_detail/<slug:slug>/', views.product_detail, name = 'product-detail'),
    path('category-child/<slug:slug>/', views.products_by_category_children, name = 'category-child'),
    path('gifts/', views.get_gifts_list, name = 'gifts'),
    path('products_by_gift/<str:name>/', views.get_products_by_gift, name = 'products-by-gifts'),
    path('delivery_services/', views.get_delivery_services, name = 'delivery-services'),
    path('delivery_services/<str:method>/', views.get_delivery_method, name = 'delivery_services-method')
]
handler404 = 'inventory.views.handler404'
handler500 = 'inventory.views.server_error'

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('add/', views.add, name = 'add'),
    path('orders/', views.user_orders, name = 'order-list'),
    
    # ADD ONE CLICK
    path('add-one-click/', views.add_one_click, name = 'add-one-click'),
    



]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('orderplaced/', views.order_placed, name = 'order_placed'),
    path('webhook/', views.stripe_webhook),
    

    #GETTING IN ONE CLICK
    path('payment-one-click/<slug:slug>/', views.payment_one_click, name = 'payment-oneclick'),



]

inventory/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages
from django.db.models import Q
from checkout.models import Delivery
from .models import (
    Product,
    ProductInventory,
    Category,
    Media,
    BestSellingProducts
)


# FOR GIFTS IMPORT
from django.conf import settings
from .floweraura_category import GiftCategory
from .floweraura_product import GiftProduct
# END FOR GIFTS IMPORT

# FOR PRACTISE BUT IMAGES DOESNT WORK
def get_fake(request):
    products = Media.objects.select_related("product_inventory__product").filter(is_feature = True).values(
        "image", "alt_text","product_inventory__sale_price", "product_inventory__product__id", "product_inventory__product__name", "product_inventory__product__slug"
    )
    context = {
        "products": products
    }
    return render(request, 'inventory/fake.html', context)
# 


# Create your views here.

# 404 PAGE
def handler404(request, exception):
    return render(request, '404.html', status=404)
# END 404 PAGE

# 500 SERVER ERROR
def server_error(request):
    return render(request, '500.html', status=500)
# END 500 SERVER ERROR



# SEARCH FUNCTION
def search(q = None):
    query = (
        Q(product__name__icontains = q) |
        Q(brand__name__icontains = q) |
        Q(sale_price__icontains = q)
    )
    datas = ProductInventory.objects.filter(query).select_related("product")

    if len(datas) == 0:
        return 0
    return datas
# END SEARCH FUNCTION

# ALL PRODUCTS
def products(request):
    q = request.GET.get('q') or None
    if q == None:
        products = ProductInventory.objects.select_related("product")
    else:
        products = search(q)
        if products == 0:
            messages.warning(request, 'Product does not exists!')
            return redirect('inventory:list-products')
    context = {
        'products': products
    }
    return render(request, 'inventory/products.html', context)
# END ALL PRODUCTS


# BEST SELLING PRODUCTS
def get_best_selling_products(request):
    products = BestSellingProducts.objects.select_related("product").filter(quantity__gt = 1)
    context = {
        "products": products
    }
    return render(request, 'inventory/best_selling_products.html', context)
# END BEST SELLING PRODUCTS


# PRODUCTS BY CATEGORY
def products_by_category(request, slug):
    #slug = "biznes-kitaplar"
    category = get_object_or_404(Category, slug = slug) 
    products = ProductInventory.objects.filter(
        product__category__in = Category.objects.get(slug=slug).get_descendants(include_self = True)
    )
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'inventory/products_by_category.html', context)
# END PRODUCTS BY CATEGORY


# PRODUCT BY CATEGORY CHILDREN
def products_by_category_children(request, slug):
    category = get_object_or_404(Category, slug = slug)
    products = ProductInventory.objects.filter(
        product__category__in = Category.objects.get(slug=slug).get_descendants(include_self = True)
    )
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'inventory/filtered_category_for_products.html', context)
# END PRODUCT BY CATEGORY CHILDREN


# PRODUCT DETAIL
def product_detail(request, slug):
    product = get_object_or_404(ProductInventory.objects.select_related("product", "brand"), product__slug = slug)
    context = {
        'product': product
    }
    return render(request, 'inventory/product_detail.html', context)
# END PRODUCT DETAIL





# GIFT IDEAS

def get_data_from_floweraura(url):
    data = GiftCategory(url=url)
    return data


def get_gifts(num: int):
    url = settings.FLOWERAURA_URL
    data = get_data_from_floweraura(url)
    return data.filter_gift(num)



def get_gifts_list(request):
    context = {
        "gifts_hampers": get_gifts(0),
        "for_hers": get_gifts(1),
        "for_hims": get_gifts(2),
        "home_kitchens": get_gifts(3),
        "fashions": get_gifts(4),
        "more_gifts": get_gifts(5),
    }
    return render(request, 'inventory/gifts.html', context)


def check_name(name: str):
    arr = ['Girlfriend', 'Wife', 'Mother', 'Sister', 'Daughter', 'Boyfriend', 'Husband', 'Father', 'Brother', 'Son', 'Boys', "Kids", "Parents"]
    if name not in arr:
        return name
    return f"For {name}"


def get_products_by_gift(request, name):
    url = settings.FLOWERAURA_URL
    products = GiftProduct(url)
    checked_name = check_name(name)
    context = {
        'gift': name,
        'products': products.get_products(checked_name),
    }
    return render(request, 'inventory/products_by_gift.html', context)


# END GIFT IDEAS


# DELIVERY SERVICE
def get_delivery_services(request):
    deliveries = Delivery.objects.all()
    page = "delivery"
    context = {
        "deliveries": deliveries,
        "page":page
    }
    return render(request, 'inventory/delivery_services.html', context)



def get_delivery_method(request, method):
    deliveries = Delivery.objects.filter(delivery_method = method)
    page = "method"
    context = {
        "deliveries": deliveries,
        "page":page
    }
    return render(request, 'inventory/delivery_services.html', context)


# END DELIVERY SERVICE

templates/inventory/best_selling_products.html
{% extends 'base.html' %}



{% block title %}Best Selling Products{% endblock %}


{% block content %}

<div class="bg-light mb-5 p-3 mt-5">
    <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-5 g-3">
      {% for product in products %}
      <div class="col">
        <div class="card shadow-sm border_radius">
          {% for image in product.product.media_product_inventory.all %}
            {% if image.is_feature %}
              <img src="{{ image.image.url }}" alt="{{ image.alt_text }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
            {% endif %}
          {% endfor %}
  
          <!-- // Images  -->
          <div class="card-body">
            <p class="text-center"><a href="{% url 'inventory:product-detail' product.product.product.slug %}" class="card-text product__name_ ">{{ product.product.product.name }}.</a></p>
            <div class="d-flex justify-content-between align-items-center mb-2">
              <div class="btn-group">
                <!-- wishlist btn -->
                <button type="button" id="wishlist-button" data-id="{{ product.id }}" class="wishlist_btn__ {% if product.is_wishlist %} text-danger {% endif %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                </button>
                <!-- wishlist -->
              </div>
              <small class="text-muted"><b>${{ product.product.sale_price }}</b></small>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-2">
                <a href="{% url 'payment:payment-oneclick' product.product.product.slug %}" class="btn signup_btn__ mt-1 w-50">buy now</a>
                <small class="sales_quantity">{{ product.quantity}} sold</small>
            </div>

          </div>
        </div>
      </div>
      {% empty %}
        <h4 class="text-center">Empty</h4>
      {% endfor %}
    </div>
  </div>
  <!-- WISHLIST SCRIPT -->
  <script>
      $(document).on('click', '#wishlist-button', function(e){
          e.preventDefault()
          //const product_id = $(this).attr("data-id")
          $.ajax({
            type: "POST",
            url: '{% url "wishlist:add" %}',
            data:{
              product_id: $(this).attr("data-id"),
              csrfmiddlewaretoken: '{{ csrf_token }}',
              action: 'post'
            },
            success: function(response){
              document.getElementById('wishlist_how_many').textContent = response.how_many
              window.location.reload() //This is reload method help us to refresh page
            },
            error: function(error){
              console.log(error)
            }
          })
          
      })
  </script>
  <!-- END WISHLIST SCRIPT -->

{% endblock content %}

templates/inventory/delivery_services.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Delivery Service
{% endblock title %}

{% block content %}

<style>
    .delivery_method{
        font-size: 17px;
        font-weight: 700;
        color: black;
    }
</style>

<div class="nav-scroller py-1 mb-2 bg-light mt-3 mb-2">
    <div class="nav d-flex mx-4">
            <a class="p-2 delivery_method mx-4" href="{% url 'inventory:delivery_services-method' 'IS'%}">In Store</a>
            <a class="p-2 delivery_method mx-4" href="{% url 'inventory:delivery_services-method' 'HD'%}">Home Delivery</a>
            <a class="p-2 delivery_method mx-4" href="{% url 'inventory:delivery_services-method' 'DD'%}">Digital Delivery</a>
    </div>
  </div>
</div>

{% if page == 'delivery' %}
<main class="container">
  <div class="p-4 p-md-5 mb-4 rounded text-bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">Delivery Service</h1>
      <p class="lead my-3">Delivery is the process of transporting goods from a source location to a predefined destination. Cargo is primarily delivered via roads and railroads on land, shipping lanes on the sea, and airline networks in the air.</p>
    </div>
  </div>

  <div class="row mb-2">
    {% for delivery in deliveries %}
        <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success text-center">{{ delivery.delivery_name}}</strong>
            <h3 class="mb-0 "><small class="text-primary">Delivery price:</small> <b>${{ delivery.delivery_price}}</b></h3>
            <div class="mb-1 text-muted">{{ delivery.delivery_timeframe}}</div>
            <p class="mb-auto">We deliver your products to any location, request a driver to collect your Parcel and deliver it to your end customer around {{ delivery.delivery_window}}!</p>
            </div>
        </div>
        </div>
    {% endfor %}
  </div>
</main>
{% else %}

<main class="container mt-2">  
    <div class="row mb-2">
      {% for delivery in deliveries %}
          <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-success text-center">{{ delivery.delivery_name}}</strong>
              <h3 class="mb-0 "><small class="text-primary">Delivery price:</small> <b>${{ delivery.delivery_price}}</b></h3>
              <div class="mb-1 text-muted">{{ delivery.delivery_timeframe}}</div>
              <p class="mb-auto">We deliver your products to any location, request a driver to collect your Parcel and deliver it to your end customer around {{ delivery.delivery_window}}!</p>
              </div>
          </div>
          </div>
          {% empty %}
            <b><small class="text-primary text-center">No Delivery Yet</small></b>
      {% endfor %}
    </div>
  </main>

{% endif %}

{% endblock content %}

templates/inventory/fake.html
{% extends 'base.html' %}
{% load static %}


{% block title %}All products{% endblock %}


{% block content %}

<!-- All products  -->
<div class="bg-light mb-5 p-3 mt-5">
<div class="row row-cols-2 row-cols-sm-3 row-cols-lg-5 g-3">
  {% for product in products %}
  <div class="col">
    <div class="card shadow-sm border_radius">
          <img src="{{ product.image.url }}" alt="{{ product.alt_text }}" class="bd-placeholder-img card-img-top" width="100%" >
    
      <!-- // Images  -->
      <div class="card-body">
        <p class="text-center"><a href="{% url 'inventory:product-detail' product.product_inventory__product__slug %}" class="card-text product__name_ ">{{ product.product_inventory__product__name }}.</a></p>
        <div class="d-flex justify-content-between align-items-center mb-1">
          <div class="btn-group">
            <!-- wishlist btn -->
            <button type="button" id="wishlist-button" data-id="{{ product.product_inventory__product__id}}" class="wishlist_btn__ {% if product.is_wishlist %} text-danger {% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
            </button>
            <!-- wishlist -->
          </div>
          <small class="text-muted"><b>${{ product.product_inventory__sale_price }}</b></small>
        </div>
        <a href="{% url 'payment:payment-oneclick' product.product_inventory__product__slug %}" class="btn signup_btn__ mt-1 w-100">Get in one click</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<!-- WISHLIST SCRIPT -->
<script>
    $(document).on('click', '#wishlist-button', function(e){
        e.preventDefault()
        //const product_id = $(this).attr("data-id")
        $.ajax({
          type: "POST",
          url: '{% url "wishlist:add" %}',
          data:{
            product_id: $(this).attr("data-id"),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
          },
          success: function(response){
            document.getElementById('wishlist_how_many').textContent = response.how_many
            window.location.reload() //This is reload method help us to refresh page
          },
          error: function(error){
            console.log(error)
          }
        })
        
    })
</script>
<!-- END WISHLIST SCRIPT -->


{% endblock content %}

templates/inventory/filtered_category_for_products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ category.name }}
{% endblock %}


{% block content %}


<div class="row mt-5">
    <div class="row g-3">
        <div class="col-lg-10 mx-auto">
            <div class="bg-light mb-5 p-3">
                <h3 class="text-center category_name__">{{ category.name }}</h3>
                <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-4 g-3">
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm border_radius">
                    {% for image in product.media_product_inventory.all %}
                        {% if image.is_feature %}
                        <img src="{{ image.image.url }}" alt="{{ image.alt_text }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
                        {% endif %}
                    {% endfor %}
            
                    <!-- // Images  -->
                    <div class="card-body">
                        <p class="text-center"><a href="{% url 'inventory:product-detail' product.product.slug%}" class="card-text product__name_ ">{{ product.product.name }}.</a></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <!-- wishlist btn -->
                            <button type="button" id="wishlist-button" data-id="{{ product.id }}" class="wishlist_btn__ {% if product.is_wishlist %} text-danger {% endif %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                </svg>
                            </button>
                            <!-- wishlist -->
                        </div>
                        <small class="text-muted"><b>${{ product.sale_price }}</b></small>
                        </div>
                    </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    $(document).on("click", "#wishlist-button", function(e){
        e.preventDefault()
        $.ajax({
            type: "POST",
            url: '{% url "wishlist:add" %}',
            data: {
                product_id: $(this).attr("data-id"),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('wishlist_how_many').textContent = response.how_many
                window.location.reload()
            },
            error: function(error){
                console.log(error)
            }
        })
    })
</script>


{% endblock content %}

templates/inventory/products.html
{% extends 'base.html' %}



{% block title %}All products{% endblock %}


{% block content %}

<!-- All products  -->
<div class="bg-light mb-5 p-3 mt-5">
  <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-5 g-3">
    {% for product in products %}
    <div class="col">
      <div class="card shadow-sm border_radius">
        {% for image in product.media_product_inventory.all %}
          {% if image.is_feature %}
            <img src="{{ image.image.url }}" alt="{{ image.alt_text }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
          {% endif %}
        {% endfor %}

        <!-- // Images  -->
        <div class="card-body">
          <p class="text-center"><a href="{% url 'inventory:product-detail' product.product.slug %}" class="card-text product__name_ ">{{ product.product.name }}.</a></p>
          <div class="d-flex justify-content-between align-items-center mb-1">
            <div class="btn-group">
              <!-- wishlist btn -->
              <button type="button" id="wishlist-button" data-id="{{ product.id }}" class="wishlist_btn__ {% if product.is_wishlist %} text-danger {% endif %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                  </svg>
              </button>
              <!-- wishlist -->
            </div>
            <small class="text-muted"><b>${{ product.sale_price }}</b></small>
          </div>
          <a href="{% url 'payment:payment-oneclick' product.product.slug %}" class="btn signup_btn__ mt-1 w-100">Get in one click</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- WISHLIST SCRIPT -->
<script>
    $(document).on('click', '#wishlist-button', function(e){
        e.preventDefault()
        //const product_id = $(this).attr("data-id")
        $.ajax({
          type: "POST",
          url: '{% url "wishlist:add" %}',
          data:{
            product_id: $(this).attr("data-id"),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
          },
          success: function(response){
            document.getElementById('wishlist_how_many').textContent = response.how_many
            window.location.reload() //This is reload method help us to refresh page
          },
          error: function(error){
            console.log(error)
          }
        })
        
    })
</script>
<!-- END WISHLIST SCRIPT -->


{% endblock content %}

templates/inventory/products_by_category.html
{% extends 'base.html' %}


{% block title %}
{{ category.name }}
{% endblock %}


{% block content %}


<div class="row mt-5">
    <div class="row g-3">
        <div class="col-lg-4 col-md-none">
            <ul class="list-group">
                <li class="list-group-item active" aria-current="true"><b>{{ category.name }}</b></li>
                {% for child in category.get_children %}
                    <li class="list-group-item category_children__"><a href="{% url 'inventory:category-child' child.slug %}">{{ child.name }} </a></li>
                {% endfor %}
            
            </ul>
        </div>
        <div class="col-lg-8">
            <div class="bg-light mb-5 p-3">
                <h3 class="text-center category_name__">{{ category.name }}</h3>
                <div class="row row-cols-2 row-cols-sm-3  row-cols-lg-4 g-3">
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm border_radius">
                    {% for image in product.media_product_inventory.all %}
                        {% if image.is_feature %}
                        <img src="{{ image.image.url }}" alt="{{ image.alt_text }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
                        {% endif %}
                    {% endfor %}
            
                    <!-- // Images  -->
                    <div class="card-body">
                        <p class="text-center"><a href="{% url 'inventory:product-detail' product.product.slug%}" class="card-text product__name_ ">{{ product.product.name }}.</a></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <!-- wishlist btn -->
                            <button type="button" id="wishlist-button" data-id="{{ product.id }}" class="wishlist_btn__ {% if product.is_wishlist %} text-danger {% endif %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                </svg>
                            </button>
                            <!-- wishlist -->
                        </div>
                        <small class="text-muted"><b>${{ product.sale_price }}</b></small>
                        </div>
                    </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>


<script>
    $(document).on("click", "#wishlist-button", function(e){
        e.preventDefault()
        $.ajax({
            type: "POST",
            url: '{% url "wishlist:add" %}',
            data: {
                product_id: $(this).attr("data-id"),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('wishlist_how_many').textContent = response.how_many
                window.location.reload()
            },
            error: function(error){
                console.log(error)
            }
        })
    })
</script>

{% endblock content %}