account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView
from .forms import (
    UserLoginForm,

)

app_name = 'account'


urlpatterns = [
    path('sign-up/', views.account_register, name = 'register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name = 'activate'),
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('edit-profile/', views.edit_profile, name = 'edit-account'),

    # LOGIN & LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name = "account/login.html",
    form_class = UserLoginForm), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/'), name = 'logout'),
    # END LOGIN & LOGOUT

    #DELETE ACCOUNT
    path('profile/delete_account/', views.delete_account, name = 'delete-account'),
    path('profile/delete-confirm/', TemplateView.as_view(template_name = 'account/delete_account.html'), name = 'delete_confirmation'),
    
    # addresses
    path('addresses/', views.view_address, name = 'addresses'),
    path('add/', views.add_address, name = 'add-address'),
    path('edit/<slug:id>/', views.edit_address, name = 'edit-address'),
    path('delete/<slug:id>/', views.delete_address, name = 'delete-address'),
    path('set_default/<slug:id>/', views.set_default, name = 'set-default'),

    path('api_page/', views.get_api_page, name = 'api-page'),

    
]

api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

app_name = "api"

urlpatterns = [
    # TOKEN
    path('auth/', obtain_auth_token),
    path('token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name = 'token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name = 'token_verify'),
    # END TOKEN

    path('search/', views.search_list_api_view, name = 'search'),
    # _________ INVENTORY APP URLS _____________
    path('category/', views.categories_api_view, name = "category-list"),
    path('products_by_category/<slug:slug>/', views.products_api_view_by_category, name = 'products-by-category'),
    path('products_category_child/<slug:slug>/', views.products_api_view_by_category_child, name = "product-detail-by-categorychild"),
    path('product_detail/<slug:slug>/', views.product_detail_api_view, name = 'product-detail'),
    path('images/<int:id>/', views.media_images_api_view, name = 'media-images'),
    # _________ END INVENTORY APP URLS _____________

    # _________ ACCOUNT APP URLS _____________
    path('customers/', views.customers_api__get_view, name = 'customers'),
    path('customer/addresses/<int:id>/', views.addresses_api_get_view, name = 'customer-addresses'),
    path('customer/address_detail/<slug:id>/', views.address_api_get_view, name = 'address-detail'),
    # _________ END ACCOUNT APP URLS _____________

    # _________ CHECKOUT APP URLS _____________
    path('deliveries/', views.deliveries_api_view_get, name = 'delivery-list'),
    path('delivery_detail/<int:id>/', views.DeliveryRetrieveApiView.as_view(), name = 'delivery-detail'),
    # _________ END CHECKOUT APP URLS _____________
    
    # _________ ORDERS APP URLS _____________
    path('orders/<int:id>/', views.orders_api_view_get, name = 'orders'),
    path('order/<int:id>/', views.order_api_view_get, name = 'order-detail'),
    path('items/<int:id>/', views.orderitems_api_view_get, name = 'order-items'),
    path("item/<int:id>/", views.orderitem_api_view_get, name = 'item-detail'),

    # _________ END ORDERS APP URLS _____________
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_list, name = 'list'),
    path('add/', views.add_basket, name = 'add_to_basket'),
    path('update/', views.update_basket, name = 'update_basket'),
    path('remove/', views.delete_basket, name = 'delete_basket'),
    #DELIVERY OPTIONS
    path('udpate_delivery/', views.basket_update_delivery, name = "basket-update-delivery"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include('inventory.urls', namespace='inventory')),
    path('basket/', include('basket.urls', namespace="basket")),
    path('account/', include('account.urls', namespace="account")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlist")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    
    # API
    path("api/", include("api.urls", namespace="api")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

inventory/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500
from . import views

app_name = 'inventory'



urlpatterns = [
    path('', views.products, name = 'list-products'),
    path('best_selling/', views.get_best_selling_products, name = 'best-products'),
    path('list/', views.get_fake),
    path('products/<slug:slug>/', views.products_by_category, name = 'products-by-category'),
    path('product_detail/<slug:slug>/', views.product_detail, name = 'product-detail'),
    path('category-child/<slug:slug>/', views.products_by_category_children, name = 'category-child'),
    path('gifts/', views.get_gifts_list, name = 'gifts'),
    path('products_by_gift/<str:name>/', views.get_products_by_gift, name = 'products-by-gifts'),
    path('delivery_services/', views.get_delivery_services, name = 'delivery-services'),
    path('delivery_services/<str:method>/', views.get_delivery_method, name = 'delivery_services-method')
]
handler404 = 'inventory.views.handler404'
handler500 = 'inventory.views.server_error'

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('add/', views.add, name = 'add'),
    path('orders/', views.user_orders, name = 'order-list'),
    
    # ADD ONE CLICK
    path('add-one-click/', views.add_one_click, name = 'add-one-click'),
    



]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}O-bazar{% endblock title %}</title>
    <!-- BOOTSTRAP SDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- END BOOTSTRAP SDN -->

    <!-- FONT-AWESOME SDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- END FONT-AWESOME SDN -->

    <!-- LOCAL STYLES -->
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles2.css'%}">
    <!-- END -->

    <!-- AJAX SDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- END AJAX SDN -->

  </head>
  
  <body>
    <!-- Header side -->
    {% include 'headers.html' %}
    <!-- Header side -->
    
    <div class="container">
        <!-- MESSAGE  -->
      {% if messages %}
        {% for message in messages %}
            <div class="alert mt-2 mb-1 alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}!</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
    <!-- END MESSAGE -->
  </div>
    <div class="container font-monospace">
        {% block content %}

        {% endblock content %}
    </div>

     <!-- Footer side -->
     {% include 'footer.html' %}
     <!-- Footer side -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
      <div class="col mb-3">
        <a href="/" id="footer_section" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
          <b style="color: red;" class="me-2">O</b>  bazar
        </a>
        <p class="text-muted">&copy; 2023</p>
      </div>
  
      <div class="col mb-3">
  
      </div>
  
      <div class="col mb-3">
        <h5>Features</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Cool Stuff</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
  
      <div class="col mb-3">
        <h5>Resources</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
  
      <div class="col mb-3">
        <h5>About</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
    </footer>
</div>

templates/headers.html
      {% load static %}
      <!-- banner bg main start -->
<nav>
  <div class="banner_bg_main pb-5">
    <!-- header top section start -->
    <div class="container">
       <div class="header_section_top">
          <div class="row">
             <div class="col-sm-12">
                <div class="custom_menu">
                   <ul>
                      <li><a href="{% url 'inventory:best-products'%}">Best Selling</a></li>
                      <li><a href="{% url 'inventory:gifts'%}">Gift Ideas</a></li>
                      <li><a href="{% url 'account:api-page'%}"><b class="text-danger">O</b> bazar API</a></li>
                      <li><a href="{% url 'inventory:delivery-services'%}">Delivery Service</a></li>
                   </ul>
                </div>
             </div>
          </div>
       </div>
    </div>
    <!-- header top section start -->
    <!-- logo section start -->
    <div class="logo_section">
       <div class="container">
          <div class="row">
             <div class="col-sm-12">
                <div class="logo"><a href="{% url 'inventory:list-products'%}" class="text-decoration-none logo_o_bazar"><b style="color: red;">O</b> bazar </a></div>
             </div>
          </div>
       </div>
    </div>
    <!-- logo section end -->
    <!-- header section start -->
    <div class="header_section">
       <div class="container">
          <div class="containt_main">
             <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{% url 'inventory:list-products'%}">Home</a>
                {% for cat in categories %}
                  <a class="dropdown-item" href="{% url 'inventory:products-by-category' cat.slug %}">{{ cat.name }}</a>
                {% endfor %}
             </div>
             <span class="toggle_icon" onclick="openNav()"><img src="{% static 'toggle-icon.png'%}"></span>

             <div class="main">
                <!-- Another variation with a button -->
                <form action="{% url 'inventory:list-products'%}" method="get">
                  <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search">
                    <div class="input-group-append">
                       <button class="btn btn-secondary" type="submit" style="background-color: #f23322; border-color:#f22222 ">
                       <i class="fa fa-search"></i>
                       </button>
                    </div>
                  </div>
                </form>
             </div>
             <div class="header_box">
              <!-- DASHBOARD LOGIN LOGOUT -->
                <div class="dropdown dashboard_login_logout">
                  <a href="#" class="dashboard_a" id = "navbarDropdown" role="button"
                  data-bs-toggle="dropdown" aria-expanded="false">
                      <b class="small hello_username__">Hello,
                        {% if request.user.is_authenticated %}
                            {{ request.user.user_name }}
                        {% else %}
                            Login
                        {% endif %}
                      </b><br>
                      <span class="fs15 fw200 account_lists__"><b> Dashboard &amp; Lists</b></span>
                  </a>
                  <!-- Drop down menu -->
                  <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                    <div class="card border-0">
                      <div class="card-body">
                        <h6 class="card-title my_dashboard___"><b>My Dashboard</b></h6>
                        <ul class="list-group list-group-flush dropdown-account-link">
                          {% if request.user.is_authenticated %}
                            <a href="{% url 'account:dashboard'%}" class="btn___ text-reset small list-group-item p-0 pb-1 border=0 dropdown-account-link">Your Account</a>
                            <a href="{% url 'orders:order-list'%}" class="btn___ text-reset small list-group-item p-0 pb-1 border=0 dropdown-account-link">Orders</a>
                            <a href="{% url 'account:logout'%}" class="btn___ text-reset small list-group-item p-0 pb-1 border=0 dropdown-account-link">Sing Out</a>
                          {% else %}
                          <a href="{% url 'account:login'%}" class="btn___ text-reset small list-group-item p-0 pb-1 border=0 dropdown-account-link">Sign In</a>
                          {% endif %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- END DASHBOARD LOGIN LOGOUT -->

                <!-- WISHLIST & BASKET -->
                <div class="login_menu">
                   <ul>
                    <!-- WISHLIST BUTTON -->
                      <li>
                        <a class="position-relative icon__" href="{% url 'wishlist:list'%}">
                          <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                          </svg>
                          <span id="wishlist_how_many" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {% if wishlist|length > 0%}
                                {{ wishlist|length }}
                            {% else %}
                                0
                            {% endif %}
                            <span class="visually-hidden">unread messages</span>
                          </span>
                        </a>
                      </li>
                       <!-- END WISHLIST BUTTON -->
                       <!-- BASKET BUTTON -->
                      <li class="mx-2">
                        <a class="position-relative icon__" href="{% url 'basket:list'%}">
                          <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                          </svg>
                          <span id="total_quantity" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {% if basket|length > 0 %}
                                {{ basket|length }}
                            {% else %}
                                0
                            {% endif %}
                            <span class="visually-hidden">unread messages</span>
                          </span>
                        </a>
                      </li>
                      <!-- END BASKET BUTTON -->
                   </ul>
                </div>
                <!-- END WISHLIST & BASKET -->
             </div>
          </div>
       </div>
    </div>
    <!-- header section end -->
 </div>
</nav>
     <!-- banner bg main end -->

     <script>
      function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
      }
      
      function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
      }
   </script>