account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView
from .forms import (
    UserLoginForm,

)

app_name = 'account'


urlpatterns = [
    path('sign-up/', views.account_register, name = 'register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name = 'activate'),
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('edit-profile/', views.edit_profile, name = 'edit-account'),

    # LOGIN & LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name = "account/login.html",
    form_class = UserLoginForm), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/'), name = 'logout'),
    # END LOGIN & LOGOUT

    #DELETE ACCOUNT
    path('profile/delete_account/', views.delete_account, name = 'delete-account'),
    path('profile/delete-confirm/', TemplateView.as_view(template_name = 'account/delete_account.html'), name = 'delete_confirmation'),
    
    # addresses
    path('addresses/', views.view_address, name = 'addresses'),
    path('add/', views.add_address, name = 'add-address'),
    path('edit/<slug:id>/', views.edit_address, name = 'edit-address'),
    path('delete/<slug:id>/', views.delete_address, name = 'delete-address'),
    path('set_default/<slug:id>/', views.set_default, name = 'set-default'),

    path('api_page/', views.get_api_page, name = 'api-page'),

    
]

api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

app_name = "api"

urlpatterns = [
    # TOKEN
    path('auth/', obtain_auth_token),
    path('token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name = 'token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name = 'token_verify'),
    # END TOKEN

    path('search/', views.search_list_api_view, name = 'search'),
    # _________ INVENTORY APP URLS _____________
    path('category/', views.categories_api_view, name = "category-list"),
    path('products_by_category/<slug:slug>/', views.products_api_view_by_category, name = 'products-by-category'),
    path('products_category_child/<slug:slug>/', views.products_api_view_by_category_child, name = "product-detail-by-categorychild"),
    path('product_detail/<slug:slug>/', views.product_detail_api_view, name = 'product-detail'),
    path('images/<int:id>/', views.media_images_api_view, name = 'media-images'),
    # _________ END INVENTORY APP URLS _____________

    # _________ ACCOUNT APP URLS _____________
    path('customers/', views.customers_api__get_view, name = 'customers'),
    path('customer/addresses/<int:id>/', views.addresses_api_get_view, name = 'customer-addresses'),
    path('customer/address_detail/<slug:id>/', views.address_api_get_view, name = 'address-detail'),
    # _________ END ACCOUNT APP URLS _____________

    # _________ CHECKOUT APP URLS _____________
    path('deliveries/', views.deliveries_api_view_get, name = 'delivery-list'),
    path('delivery_detail/<int:id>/', views.DeliveryRetrieveApiView.as_view(), name = 'delivery-detail'),
    # _________ END CHECKOUT APP URLS _____________
    
    # _________ ORDERS APP URLS _____________
    path('orders/<int:id>/', views.orders_api_view_get, name = 'orders'),
    path('order/<int:id>/', views.order_api_view_get, name = 'order-detail'),
    path('items/<int:id>/', views.orderitems_api_view_get, name = 'order-items'),
    path("item/<int:id>/", views.orderitem_api_view_get, name = 'item-detail'),

    # _________ END ORDERS APP URLS _____________
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_list, name = 'list'),
    path('add/', views.add_basket, name = 'add_to_basket'),
    path('update/', views.update_basket, name = 'update_basket'),
    path('remove/', views.delete_basket, name = 'delete_basket'),
    #DELIVERY OPTIONS
    path('udpate_delivery/', views.basket_update_delivery, name = "basket-update-delivery"),


]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('deliverychoices/', views.deliverychoices, name = 'deliverychoices'),
    path('delivery_address/', views.delivery_address, name = 'delivery_address'),
    path('pay/', views.pay_securely, name = 'pay'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include('inventory.urls', namespace='inventory')),
    path('basket/', include('basket.urls', namespace="basket")),
    path('account/', include('account.urls', namespace="account")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlist")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    
    # API
    path("api/", include("api.urls", namespace="api")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Delivery(models.Model):
    """
    The Delivery Table
    """
    DELIVERY_CHOICES = [
        ('IS', 'In Store'),
        ('HD', 'Home Delivery'),
        ('DD', 'Digital Delivery'),
    ]

    delivery_name = models.CharField(verbose_name=_("delivery name"), help_text=_("required"), max_length=255)
    delivery_price = models.DecimalField(
        verbose_name=_("Delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name":{
                "max_length": _("The price must be between 0 and 999.99")
            }
        },
        max_digits=5,
        decimal_places=2
    )

    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )

    #delivery_timeframe means when your product will be your hand like that
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )

    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )

    order = models.IntegerField(
        verbose_name=_("List Order"),
        help_text=_("Required"),
        default=0
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    
    def __str__(self):
        return self.delivery_name

checkout/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages
from basket.basket import Basket
from .models import Delivery
from account.models import Address
import stripe
# Create your views here.

# DELIVERY CHOICES
@login_required
def deliverychoices(request):
    deliveryoptions = Delivery.objects.filter(is_active = True)
    context = {
        'deliveryoptions': deliveryoptions
    }
    return render(request, 'checkout/delivery_choices.html', context)
# END DELIVERY CHOICES


# DELIVERY ADDRESS
@login_required
def delivery_address(request):
    session = request.session

    if 'purchase' not in request.session:
        messages.info(request, "Please select delivery option.")
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    addresses = Address.objects.filter(customer = request.user).order_by('-default')
    if addresses:
        if 'address' not in request.session:
            session['address'] = {'address_id': str(addresses[0].id)}
        else:
            session['address']['address_id'] = str(addresses[0].id)
            session.modified = True

    context = {
        'addresses': addresses
    }
    return render(request, 'checkout/delivery_address.html', context)
# END DELIVERY ADDRESS


# GET CLIENT SECRET
def get_client_secret(request):
    basket = Basket(request)
    total_price = str(basket.get_total_and_delivery_price()).replace(".", "")
    total_price_int = int(total_price)
    stripe.api_key = "sk_test_51MOjpRDh4Pu0qkGJK8Qe4I9X2GERDaEV62lSzW1FLC4dDoBnp35fOzvjzW2ErnnRPmFTjR5RpURp1RgudjEjoZ9100xlkFvlQ2"
    intent = stripe.PaymentIntent.create(
        amount = total_price_int,
        currency = "usd",
        metadata = {'userid': request.user.id}
    )
    return intent.client_secret
# END GET CLIENT SECRET



# PAY YOUR PRODUCT 
@login_required
def pay_securely(request):
    address_id = request.session.get('address')['address_id']
    delivery_id = request.session.get("purchase")['delivery_id']
    delivery = Delivery.objects.get(id = delivery_id)
    address = Address.objects.filter(id =address_id,customer = request.user, default = True).first()
    if not address:
        previous_url = request.META.get("HTTP_REFERER")
        if "delivery_address" in previous_url:
            messages.warning(request, "You didn't select your address.Select your address.")
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
    # GET CLIENT SECRET
    client_secret = get_client_secret(request)
        
    context = {
        "address": address,
        "delivery":delivery,
        "client_secret": client_secret
    }
    return render(request, 'checkout/pay_securely.html', context)
# END PAY YOUR PRODUCT

templates/checkout/delivery_address.html
{% extends 'base.html' %}


{% block title %}
Delivery Address
{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="col-12">
        <h1 class="h2 create_account__">Delivery Address</h1>
    </div>
    <div class="col-12">
        <b>Please select your</b> <b class="text-danger">delivery address</b>
    </div>
    <hr>

    <div class="container">
        <div class="row g-3">
            {% if addresses|length == 0%}
                <div class="col-12">There are no delivery addresses!!, <a href="{% url 'account:add-address' %}">Add address</a></div>
            {% else %}
                <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                        <!-- Sub total -->
                    <div class="d-flex bg-highlight ms-0">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Sub Total:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                            <!-- Tomende basket context_processory jardeminde islengen ozin bilesin -->
                        <span id="sub_total" class="fw-bold h5">{{ basket.get_total_price }}</span>
                        </div>
                    </div>
                    <!-- Delivery cost -->
                    <div class="d-flex bg-highlight">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Delivery Cost:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                        <span id="delivery_cost" class="fw-bold h5">{{ basket.get_delivery_price }}</span>
                        </div>
                    </div>
                    <!-- Total -->
                    <div class="d-flex bg-highlight">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Total:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                        <span id="total" class="fw-bold h5">{{ basket.get_total_and_delivery_price }}</span>
                        </div>
                    </div>
                    <!-- Pay button -->
                    <a role="button" href="{% url 'checkout:pay'%}" class="btn signup_btn__ fw-bold w-100" type="button">
                        Pay Securely
                    </a>
                </div>
                <div class="col-md-7 col-lg-8">
                    {% for address in addresses %}
                        {% if not address.default %}
                            <h1 class="h5 pt-4 create_account__">Other Addressess</h1>
                        {% endif  %}
                        <div class="card-mb-3 border-1 rounded-0 me-md-4" data-index="{{ address.id }}">
                            <div class="row g-0">
                                <div class="col">
                                    <div class="card pb-3 rounded-0">
                                        <div class="card-header bg-white small text-muted">
                                            {% if address.default %}
                                                Selected
                                            {% endif %}
                                            &nbsp;
                                        </div>
                                        <div class="card-body small pb-1">
                                            <p class="card-text m-0 fw-bold">{{ address.full_name }}</p>
                                            <p class="card-text m-0 fw-bold">{{ address.address_line }}</p>
                                            <p class="card-text m-0 fw-bold">{{ address.address_line2 }}</p>
                                            <p class="card-text m-0 fw-bold">{{ address.town_city }}</p>
                                            <p class="card-text m-0 fw-bold">{{ address.post_code }}</p>
                                            <p class="card-text m-0 fw-bold">Phone: {{ address.phone }}</p>
                                            <div class="pt-5">
                                                <a href="{% url 'account:edit-address' address.id %}" class="text-decoration-none">Edit</a>|
                                                {% if not address.default %}
                                                <a href="{% url 'account:set-default' address.id%}" class="text-decoration-none">Select</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>

            {% endif %}
        </div>
    </div>

</div>


{% endblock content %}

templates/checkout/delivery_choices.html
{% extends 'base.html' %}


{% block title %}
Delivery Options
{% endblock %}


{% block content %}

<div class="container py-5">
    <div class="col-12">
        <h1 class="h2 create_account__">Delivery Options</h1>
    </div>
    <div class="col-12">
        <p><b>Select your</b> <b class="text-danger">Delivery options</b></p>
    </div>
    <hr>
</div>
<div class="container">
    <div class="row g-3">
        {% if deliveryoptions|length == 0 %}
            <div class="col-12">There are no delivery options <a href="{% url 'store:home' %}">Shop</a></div>
        
        {% else %}
            <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                <!-- TOTAL PRICE  -->
                <div class="d-flex bg-highlight ms-0">
                    <div class="p-2 flex-grow-1 bg-highlight create_account__">Sub Total:</div>
                    <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                        <!-- BELLOW BASKET TOTAL PRICE  -->
                    <span id="sub_total" class="fw-bold h5">{{ basket.get_total_price }}</span>
                    </div>
                </div>
                <!-- Delivery cost -->
                <div class="d-flex bg-highlight">
                    <div class="p-2 flex-grow-1 bg-highlight create_account__">Delivery Cost:</div>
                    <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                    <span id="delivery_cost" class="fw-bold h5">{{ basket.get_delivery_price }}</span>
                    </div>
                </div>
                <!-- Total -->
                <div class="d-flex bg-highlight">
                    <div class="p-2 flex-grow-1 bg-highlight create_account__">Total:</div>
                    <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                    <span id="total" class="fw-bold h5">{{ basket.get_total_and_delivery_price }}</span>
                    </div>
                </div>
                <!-- Pay button -->
                <a role="button" href="{% url 'checkout:delivery_address' %}" class="btn signup_btn__ fw-bold w-100" type="button">
                    Checkout your address
                </a>
            </div>
            <div class="col-md-7 col-lg-8">
                {% for option in deliveryoptions %}
                    <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{ option.id }}">
                        <div class="row g-0">
                            <div class="col-md-2 ps-3 ps-md-4 ">
                                <!-- icons -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
                                    <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                </svg>

                            </div>
                            <div class="col-md-9 ps-md-1">
                                <div class="card-body p-1">
                                    <p class="card-text ps-2 mb-1 pt-1 fw-bold create_account__">{{ option.delivery_name }}</p>
                                    <p class="card-text ps-2 pb-3">Your order should be delivered within {{ option.delivery_timeframe }}.</p>

                                </div>
                            </div>
                            <div class="col-md-1 ps-md-1">
                                <input type="radio"   name="deliveryOption" id="{{ option.id }}" class="align-middle h-100" value="{{ option.id }}">
                            </div>

                        </div>

                    </div>
                {% endfor %}
            </div>
        
        {% endif %}
        
    </div>
</div>


<script>
    $(`input[type=radio][name=deliveryOption]`).on('change', function(e){
        e.preventDefault()
        $.ajax({
            type: "POST",
            url: "{% url 'basket:basket-update-delivery'%}",
            data:{
                deliveryoption: $(this).val(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: "post"
            },
            success: function(response){
                document.getElementById('delivery_cost').innerHTML = response.delivery_price
                document.getElementById('total').innerHTML = response.total
            },
            error: function(error){
                console.log(response)
            }
        })
    })
</script>

{% endblock %}

templates/checkout/pay_securely.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
Pay
{% endblock %}


{% block content %}

<div class="container py-5">
    <div class="col-12">
        <h1 class="h2 create_account__">Pay for your product</h1>
    </div>
    <hr>

    <div class="container">
        <div class="row g-3">
                <div id="payment-form" class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                    <!-- Error messages in this element -->
                    <div class="a" id="card-errors" role="alert"></div>

                        <!-- Sub total -->
                    <div class="d-flex bg-highlight ms-0">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Sub Total:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                            <!-- Tomende basket context_processory jardeminde islengen ozin bilesin -->
                        <span id="sub_total" class="fw-bold h5">{{ basket.get_total_price }}</span>
                        </div>
                    </div>
                    <!-- Delivery cost -->
                    <div class="d-flex bg-highlight">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Delivery Cost:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                        <span id="delivery_cost" class="fw-bold h5">{{ basket.get_delivery_price }}</span>
                        </div>
                    </div>
                    <!-- Total -->
                    <div class="d-flex bg-highlight">
                        <div class="p-2 flex-grow-1 bg-highlight create_account__">Total:</div>
                        <div class="p-2 bg-highlight"><span class="fw-bold h5">$</span>
                        <span id="total" class="fw-bold h5">{{ basket.get_total_and_delivery_price }}</span>
                        </div>
                    </div>
                    <!-- PAYMENT -->
                    <!-- PAYMENT  -->
                                <hr>
                                <h4 class="mb-3 create_account__">Payment</h4>
                                <label for="card-element"><b>Credit or debit card</b></label>
                                <div id="card-element" class="form-control form-control-payment">
                                    <!-- PAYMENT ELEMENTS WILL APPEAR HERE -->
                                </div>
                                <button type="submit" id="submit" class="mt-3 btn signup_btn__ w-100" data-secret="{{ client_secret }}">Pay</button>
                    <!-- END PAYMENT  -->
                    <!-- END PAYMENT  -->
                </div>
                <div class="col-md-7 col-lg-8">
                        <div class="card-mb-3 border-1 rounded-0 me-md-4" data-index="{{ address.id }}">
                            <div class="row g-0">
                                <div class="col">
                                    <div class="card pb-3 rounded-0">
                                        <div class="card-header bg-white small text-muted">
                                            Your Address
                                            &nbsp;
                                        </div>
                                        <div class="card-body small pb-1">
                                            <p class="card-text m-0 fw-bold" id="firstName">{{ address.full_name }}</p>
                                            <p class="card-text m-0 fw-bold" id="custAdd">{{ address.address_line }}</p>
                                            <p class="card-text m-0 fw-bold" id="custAdd2">{{ address.address_line2 }}</p>
                                            <p class="card-text m-0 fw-bold">{{ address.town_city }}</p>
                                            <p class="card-text m-0 fw-bold" id="postCode">{{ address.postcode }}</p>
                                            <p class="card-text m-0 fw-bold">Phone: {{ address.phone }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END ADDRESS -->
                        <!--  DELIVERY -->
                        <div class="card-mb-3 card p-3 mt-3 border-1 rounded-0 me-md-4">
                            <div class="row g-0">
                                <div class="card-header bg-white small text-muted">
                                    Your Delivery Company
                                    &nbsp;
                                </div>
                                <div class="card-body">
                                    <div class="col-md-2 ps-3 ps-md-4 ">
                                        <!-- icons -->
                                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
                                            <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                        </svg>
                                    </div>
                                    <div class="col-md-9 ps-md-1">
                                        <div class="card-body p-1">
                                            <p class="card-text ps-2 mb-1 pt-1 fw-bold create_account__">{{ delivery.delivery_name }}</p>
                                            <p class="card-text ps-2 pb-3"><b>Your order should be delivered within {{ delivery.delivery_timeframe }}.</b></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END DELIVERY -->
                </div>
        </div>
    </div>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
    const CSRF_TOKEN = '{{ csrf_token }}'
</script>
<script src="{% static 'js/payment/index.js'%}"></script>


{% endblock content %}