api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

app_name = "api"

urlpatterns = [
    # TOKEN
    path('auth/', obtain_auth_token),
    path('token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name = 'token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name = 'token_verify'),
    # END TOKEN

    path('search/', views.search_list_api_view, name = 'search'),
    # _________ INVENTORY APP URLS _____________
    path('category/', views.categories_api_view, name = "category-list"),
    path('products_by_category/<slug:slug>/', views.products_api_view_by_category, name = 'products-by-category'),
    path('products_category_child/<slug:slug>/', views.products_api_view_by_category_child, name = "product-detail-by-categorychild"),
    path('product_detail/<slug:slug>/', views.product_detail_api_view, name = 'product-detail'),
    path('images/<int:id>/', views.media_images_api_view, name = 'media-images'),
    # _________ END INVENTORY APP URLS _____________

    # _________ ACCOUNT APP URLS _____________
    path('customers/', views.customers_api__get_view, name = 'customers'),
    path('customer/addresses/<int:id>/', views.addresses_api_get_view, name = 'customer-addresses'),
    path('customer/address_detail/<slug:id>/', views.address_api_get_view, name = 'address-detail'),
    # _________ END ACCOUNT APP URLS _____________

    # _________ CHECKOUT APP URLS _____________
    path('deliveries/', views.deliveries_api_view_get, name = 'delivery-list'),
    path('delivery_detail/<int:id>/', views.DeliveryRetrieveApiView.as_view(), name = 'delivery-detail'),
    # _________ END CHECKOUT APP URLS _____________
    
    # _________ ORDERS APP URLS _____________
    path('orders/<int:id>/', views.orders_api_view_get, name = 'orders'),
    path('order/<int:id>/', views.order_api_view_get, name = 'order-detail'),
    path('items/<int:id>/', views.orderitems_api_view_get, name = 'order-items'),
    path("item/<int:id>/", views.orderitem_api_view_get, name = 'item-detail'),

    # _________ END ORDERS APP URLS _____________
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_list, name = 'list'),
    path('add/', views.add_basket, name = 'add_to_basket'),
    path('update/', views.update_basket, name = 'update_basket'),
    path('remove/', views.delete_basket, name = 'delete_basket'),
    #DELIVERY OPTIONS
    path('udpate_delivery/', views.basket_update_delivery, name = "basket-update-delivery"),


]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('deliverychoices/', views.deliverychoices, name = 'deliverychoices'),
    path('delivery_address/', views.delivery_address, name = 'delivery_address'),
    path('pay/', views.pay_securely, name = 'pay'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include('inventory.urls', namespace='inventory')),
    path('basket/', include('basket.urls', namespace="basket")),
    path('account/', include('account.urls', namespace="account")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlist")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    
    # API
    path("api/", include("api.urls", namespace="api")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import JsonResponse
from inventory.models import ProductInventory
from .basket import Basket
from checkout.models import Delivery
# Create your views here.


# BASKET LIST
def basket_list(request):
    return render(request, 'basket/list.html')
# END BASKET LIST


#ADD BASKET VIEWS
def add_basket(request):
    """
    Add button this function of role is Grab product info 
    using Ajax and response JsonResponse
    """
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        quantity = int(request.POST.get('product_quantity'))
        product_id = int(request.POST.get('product_id'))
        product_inventory = get_object_or_404(ProductInventory, pk = product_id)
        basket.add(product_inventory, quantity)

        total_quantity = basket.__len__()

        response = JsonResponse({'total_qty': total_quantity})
        return response
#END ADD BASKET VIEWS


#UPDATE BASKET VIEWS
def update_basket(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_quantity = int(request.POST.get('product_quantity'))
        product_id = request.POST.get('product_id')
        basket.update_basket(product_id, product_quantity)
        total_qty = basket.__len__()
        total_price = basket.get_total_price()

        response = JsonResponse({'total_price':total_price, 'total_qty': total_qty})
        return response


#DELETE BASKET VIEWS
def delete_basket(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = request.POST.get('product_id')
        basket.remove(product_id)
        total_qty = basket.__len__()
        total_price = basket.get_total_price()

        response = JsonResponse({'total_price': total_price, 'total_qty': total_qty})
        return response
#END DELETE BASKET VIEWS
    

# DELIVERY CHANGE OPTIONS RADIO
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        delivery_id = int(request.POST.get("deliveryoption"))
        delivery = get_object_or_404(Delivery, pk = delivery_id)
        total_price = basket.basket_update_delivery(delivery_price=delivery.delivery_price)

        session = request.session
        if 'purchase' not in request.session:
            session['purchase'] = {
                'delivery_id': delivery.id
            }
        else:
            session['purchase']['delivery_id'] = delivery.id
            session.modified = True

        response = JsonResponse({
            "total": total_price,
            "delivery_price": delivery.delivery_price
        })
        return response
# END DELIVERY CHANGE OPTIONS RADIO

templates/basket/list.html
{% extends 'base.html' %}

{% block title %}
    Basket Summary
{% endblock title %}


{% block content %}
    <main class="pt-5 mb-5 px-4 px-md-0">
        <h1 class="h5 create_account__">Shopping basket</h1>
        {% if basket %}
        {% for item in basket %}
            {% with product=item.product %}
                <div class="row mb-4 border product_item" data-index="{{ product.id }}">
                    <div class="col-md-5 col-lg-5 order-md-first bg-light ">
                        {% if product.media_product_inventory %}
                            {% for image in product.media_product_inventory.all %}
                                {% if image.is_feature %}
                                    <img src="{{ image.image.url }}" width="200px" class="img-fluid mx-auto d-block p-2" alt="{{ image.alt_text }}">
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5 p-1">
                        <h1 class="mb-0 h3 text-center mt-2 mb-3">{{ product.product.name }}</h1>
                        <p><span class="create_account__ ">Brand</span>     <b>({{ product.brand.name}})</b></p>
                        <div class="border">
                            <div class="col border-bottom">
                                <div class="row p-3">
                                    <div class="col-6 create_account__">Price</div>
                                    <div class="col-6 text-end">
                                        <span class="h4 fw-bold">
                                            ${{ item.price }}
                                        </span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="row p-3">
                                        <div class="col-6">
                                            <label for="select"><b>Quantity</b></label>
                                            <select  id="select{{ product.id }}">
                                                <option selected>{{item.quantity}}</option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                        <div class="col-6 text-end">
                                            <button class="btn btn-outline-secondary" id="updateBtn" value="{{ product.id }}" type="button">Update</button>
                                            <button class="btn btn-outline-danger" id="deleteBtn" value="{{ product.id }}" type="button">Remove</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}
        <!-- TOTAL PRICE  -->
        <div class="col-12 text-end">
            <div class="h6 fw-bold create_account__">
                Total price:  <b>$<span id = 'subtotal'> {{ basket.get_total_price}}</b></span>
            </div>
        </div>
        <!-- END TOTAL PRICE -->
        <!-- CHECK OUT -->
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2">
                <!-- CHECKOUT BUTTON GO TO DELIVERY OPTIONS -->
                <a class="btn checkout_btn__" href="{% url 'checkout:deliverychoices'%}">Checkout</a>
            </div>
        </div>
        <!-- END CHECK OUT -->

        {% else %}
            <p class="text-center mt-3 product_attribute_name__ h1"><b>Empty .....</b></p>
        {% endif %}
    </main>

    <script>
        // UPDATE BASKET 
        $(document).on('click', '#updateBtn', function(e){
            e.preventDefault()
            let product_id = $(this).val()
            $.ajax({
                type: 'POST',
                url: '{% url "basket:update_basket" %}',
                data:{
                    product_id: product_id,
                    product_quantity: $(`#select${product_id} option:selected`).text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: "post"
                },
                success: function(response){
                    document.getElementById('subtotal').textContent = response.total_price
                    document.getElementById('total_quantity').textContent = response.total_qty
                },
                error: function(error){
                    console.log(error)
                }
            })
        })

        // END UPDATE BASKET 

        // DELETE BASKET FROM SESSION
        $(document).on('click', '#deleteBtn', function(e){
            e.preventDefault()
            let product_id = $(this).val()
            $.ajax({
                type: "POST",
                url: "{% url 'basket:delete_basket' %}",
                data: {
                    product_id: product_id,
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function(response){
                    $(`.product_item[data-index="${product_id}"]`).remove()
                    document.getElementById('total_quantity').textContent = response.total_qty
                    document.getElementById('subtotal').textContent = response.total_price
                },
                error: function(error){
                    console.log(error)
                }
            })
            
        })

        // END DELETE BASKET FROM SESSION
    </script>


{% endblock content %}